spring:
  datasource:
    url: jdbc:mysql://1.2.1.3306/productsappv2?useSSL=false&serverTimezone=UTC  # Update to your MySQL URL
    username: root  # Your MySQL username
    password: Researcher@03  # Your MySQL password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Ensures schema is created or updated automatically
    show-sql: true  # Shows SQL queries in the console (optional)
    database-platform: org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      enabled: false  # Disable H2 console



#spring:
#  application:
#    name: productsapp
#  datasource:
#    # Use a file-based database for persistence
#    url: jdbc:h2:mem:productsappv2
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true
#    hibernate:
#      ddl-auto: update  # This will auto-create or update your schema
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
#  h2:
#    console:
#      enabled: true
#      path: /h2-console  # Accessible via http://localhost:8080/h2-console

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    try-it-out-enabled: false
    default-model-expand-depth: -1

management:
  endpoints:
    web:
      exposure:
        include: [ "prometheus" ]
